/*
 * generated by Xtext
 */
package edu.stanford.compilers.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CoolUiModule extends edu.stanford.compilers.ui.AbstractCoolUiModule {
	public CoolUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
