/*
 * generated by Xtext
 */
package edu.stanford.compilers.ui.contentassist

import edu.stanford.compilers.ui.contentassist.AbstractCoolProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CoolProposalProvider extends AbstractCoolProposalProvider {
}
