/*
* generated by Xtext
*/
package edu.stanford.compilers;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CoolUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return edu.stanford.compilers.ui.internal.CoolActivator.getInstance().getInjector("edu.stanford.compilers.Cool");
	}
	
}
