/*
 * generated by Xtext
 */
package edu.stanford.compilers;

import org.eclipse.xtext.linking.ILinkingService;

import edu.stanford.compilers.linking.CoolLinkingService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CoolRuntimeModule extends edu.stanford.compilers.AbstractCoolRuntimeModule {

	public Class<? extends ILinkingService> bindILinkingService() {
		return CoolLinkingService.class;
	}
}
