/*
* generated by Xtext
*/
package edu.stanford.compilers;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CoolStandaloneSetup extends CoolStandaloneSetupGenerated{

	public static void doSetup() {
		new CoolStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

